### ISSUE TITLE
Meeting Times

### ISSUE THREAD

**Issue by amayadwillis** [amayadwillis/DisneySongs#6]
Amaya availability

Mon + Fri:         1:20-DIGIT400 and after DIGIT400 if need be 
Tues + Thurs:    1:30-2:50 and after 4:20 if need be
Wed:                  1:20-DIGIT 400 and 3:20-5:50ish

I could also meet in the morning (before 10:30) or in the evenings (after 6:00) over zoom :)

**Comment by wdjacca** [comment]
[FALL_2021.pdf](https://github.com/amayadwillis/DisneySongs/files/7180919/FALL_2021.pdf)

I can meet anytime that is not blocked, whether in person or over zoom doesn't matter to me.
